In [1]:
import pandas as pd
import numpy as np

In [2]:
#Introducing myself using python
print("Hello, I am Kedei Eyong, a Data Analyst.")

# My task duration (integer)
duration = 15
print(f"I am participating in a {duration} days Data Analytics Challenge.")

# My favourite analytical tools (list)
analytical_tools = ["Excel", "Python", "SQL", "Power BI"]
print(f"I really enjoy using {analytical_tools}.")

# My skills (dictionary)
my_skills = {
    "Data_Cleaning": "Expert",
    "Data_Wrangling": "Proficient",
    "Data_Analysis": "Expert",
    "Data_Visualization": "Proficient"
}
print(f"My skills include: {my_skills}")

# My weekly study hours (float)
study_period = 14.5
print(f"I study approximately {study_period} hours weekly to hone my skills.")

# Do I enjoy data visualization? (boolean)
enjoys_visualization = True
print(f"Do I enjoy data visualization? {enjoys_visualization}")

print("I love what I do.")

Hello, I am Kedei Eyong, a Data Analyst.
I am participating in a 15 days Data Analytics Challenge.
I really enjoy using ['Excel', 'Python', 'SQL', 'Power BI'].
My skills include: {'Data_Cleaning': 'Expert', 'Data_Wrangling': 'Proficient', 'Data_Analysis': 'Expert', 'Data_Visualization': 'Proficient'}
I study approximately 14.5 hours weekly to hone my skills.
Do I enjoy data visualization? True
I love what I do.


In [3]:
#Combining Data Types and basic operations
print("I am Kedei Eyong, an amazing Data Analyst.")  #string

daily_study_hours = 2.11   #Float
study_days_per_week = 7  #Integer
weekly_study_hours = daily_study_hours * study_days_per_week  #Operation statement
print(f"I practice data analytics for at least {weekly_study_hours} hours a week.")

#Dictionary
contact_info = {
    "email": "kedei.eyong@yahoo.com",
    "LinkedIn": "https://www.linkedin.com/in/kedeieyong"
}
print(f"You can connect with me for collaboration through {contact_info['email']} or {contact_info['LinkedIn']}.")

#List
hobbies = ["dancing", "singing", "playing"] 
print(f"In my free time, I enjoy {', '.join(hobbies)}.")

#Conditional logic with Boolean data
likes_liverpool = True
if likes_liverpool:
    print("Kedei is a Liverpool fan!")
else:
    print("Not a football fan!")

I am Kedei Eyong, an amazing Data Analyst.
I practice data analytics for at least 14.77 hours a week.
You can connect with me for collaboration through kedei.eyong@yahoo.com or https://www.linkedin.com/in/kedeieyong.
In my free time, I enjoy dancing, singing, playing.
Kedei is a Liverpool fan!


In [4]:
#String Operations
#F-String
name_1 = "Kedei"
profession = "a Data Analyst"
greeting = f"Hello, my name is {name_1} and I am {profession}."
print(greeting)

Hello, my name is Kedei and I am a Data Analyst.


In [5]:
#String Indexing and Slicing
name_2 = 'Kedei', 'Josephine', 'Josee', 'Alfred', 'Fred', 'Eyong'
print(name_2[1])    #indexing
print(name_2[-1])   #end indexing
print(name_2[:5])   #slicing from the beginning
print(name_2[1:3])  #slicing from index 1

Josephine
Eyong
('Kedei', 'Josephine', 'Josee', 'Alfred', 'Fred')
('Josephine', 'Josee')


In [6]:
#String Concatenation
first_name = "Kedei"
last_name = "Eyong"
name_3 = first_name + " " + last_name
print(name_3)

Kedei Eyong


In [7]:
#Other String Operations
print(len(first_name))
print(first_name.capitalize())
print(first_name.upper())
print(first_name.lower())

5
Kedei
KEDEI
kedei


In [8]:
#Data Structures

#List - used for ordered mutable elements
my_hobbies = ["dancing", "singing", "playing"]
print(my_hobbies)

#Tuples - used for ordered immutable elements
even_numbers = (2, 4, 6, 8, 10, 12, 14)
print(even_numbers)

#Dictionary - used for key value pairs
my_skills = {
    "first_name": "Kedei",
    "profession": "a Data Analyst"
}
print(my_skills)

#Set - used for unordered collection of unique elements
even_numbers = {0, 1, 6, 3, 13, 12, 31}
print(even_numbers)

['dancing', 'singing', 'playing']
(2, 4, 6, 8, 10, 12, 14)
{'first_name': 'Kedei', 'profession': 'a Data Analyst'}
{0, 1, 3, 6, 12, 13, 31}


In [9]:
#For Loop and if else statement
student_score = [79, 90, 87, 58, 64]

for score in student_score:
    if score > 75:
        print("Distinction")
    else:
        print("well done but try harder!")

for score in student_score:
    if score % 2 == 0:
        print("even number")
    else:
        print("odd number")

Distinction
Distinction
Distinction
well done but try harder!
well done but try harder!
odd number
even number
odd number
even number
even number


In [10]:
def student_score_input():
  """Prompts the student to enter subject score and returns it."""
  while True:
     try:
        student_score_input = int(input("Enter your score: "))
        return student_score_input
     except ValueError:
        print("Invalid input. Please enter a numeric value.")

# Get user input
score_data = student_score_input()
print(score_data)

Enter your score:  95


95


In [11]:
import my_module

result_1 = my_module.add(17, 1)
print(result_1)

result_2 = my_module.subtract(30, 5)
print(result_2)

result_3 = my_module.multiply(3, 5)
print(result_3)

result_4 = my_module.divide(27,3)
print(result_4)

18
25
15
9.0


In [12]:
df_1 = pd.read_csv("C:/Users/LENOVO/Desktop/Supermarket.csv")
df_1.head()

Product Identifier Supermarket Identifier Product Supermarket Identifer  \
0              NCA29            CHUKWUDI046             NCA29_CHUKWUDI046   
1              FDG53            CHUKWUDI049             FDG53_CHUKWUDI049   
2              NCN05            CHUKWUDI045             NCN05_CHUKWUDI045   
3              NCV17            CHUKWUDI046             NCV17_CHUKWUDI046   
4              FDK03            CHUKWUDI045             FDK03_CHUKWUDI045   

   Product Weight Product Fat Content  Product Shelf Visibility  \
0          10.500              Lo Fat                  0.027276   
1          10.000             Low Fat                  0.045928   
2           8.235              Lo Fat                  0.014489   
3          18.850             Low Fat                  0.016108   
4          12.600          Normal Fat                  0.074070   

         Product Type  Product Price Supermarket Opening Year  \
0           Household         428.28                     s004   
1        Frozen Foods         345.30                     2006   
2  Health and Hygiene         459.49                     s009   
3  Health and Hygiene         324.41                     s004   
4               Dairy         635.59                     s009   

  Supermarket  Size Supermarket Location Type   Supermarket Type  \
0             Small                 Cluster 1  Supermarket Type1   
1            Medium                 Cluster 1  Supermarket Type1   
2               NaN                 Cluster 2  Supermarket Type1   
3             Small                 Cluster 1  Supermarket Type1   
4               NaN                 Cluster 2  Supermarket Type1   

  Average Price per ProductType  Product Supermarket Sales  
0                    399.999418                    8983.31  
1                   388.0710941                    4893.63  
2                   367.1430293                    7323.80  
3                   367.1430293                    7541.85  
4                   409.5043429                   11445.10

In [13]:
# Numpy Operations
# Create a 2D NumPy array of shape `(2, 3)` with random integers between 1 and 50
test_array = np.random.randint(1, 51, (2, 3))
print(test_array)

[[19 21 21]
 [28 16 23]]


In [14]:
np.sum(test_array)

128

In [15]:
np.mean(test_array)

21.333333333333332

In [16]:
np.median(test_array)

21.0

In [17]:
np.max(test_array)

28

In [18]:
np.min(test_array)

16

In [19]:
print(test_array * 2)

[[38 42 42]
 [56 32 46]]


In [20]:
np.unique(test_array)

array([16, 19, 21, 23, 28])

In [21]:
new_array = np.append(test_array, 5)

In [22]:
#Boolean Array Operations
# Select elements greater than 5
greater_than_5 = new_array > 5
print("Elements greater than 5:\n", new_array[greater_than_5])

# Select elements between 15 and 40
between_15_and_40 = (new_array >= 15) & (new_array <= 40)
print("Elements between 15 and 40:\n", new_array[between_15_and_40])

# Select elements less than or equal to 20
less_than_or_equal_to_20 = new_array <= 20
print("Elements less than or equal to 20:\n", new_array[less_than_or_equal_to_20])

# Select elements that are not equal to 5
not_equal_to_5 = new_array != 5
print("Elements not equal to 5:\n", new_array[not_equal_to_5])

Elements greater than 5:
 [19 21 21 28 16 23]
Elements between 15 and 40:
 [19 21 21 28 16 23]
Elements less than or equal to 20:
 [19 16  5]
Elements not equal to 5:
 [19 21 21 28 16 23]


In [23]:
#Numpy Algebra
L = list(range(4))  # Creating a list
print("List:", L) 

test_array2 = np.array(L)   # Creating an array from the list
print("Array:", test_array2)

reshaped_arr = test_array2.reshape(1, 4)   # changing the shape of test_array2
print("reshaped:", reshaped_arr)

resized_arr = test_array2.copy()       # resizing test_array2     
resized_arr.resize(3,1)
print("resized:", resized_arr)

test_array3 = np.linspace(1, 5, 4)     # creating a new array of 4 numbers between 1 and 5)
print("new array:", test_array3)

dot_array = np.dot(test_array2, test_array3)    # multiplying two arrays [test_array2, test_array3]
print("dot_array:", dot_array)

List: [0, 1, 2, 3]
Array: [0 1 2 3]
reshaped: [[0 1 2 3]]
resized: [[0]
 [1]
 [2]]
new array: [1.         2.33333333 3.66666667 5.        ]
dot_array: 24.666666666666664


In [24]:
# Creating a pandas series
L = [0, 1, 2, 3]                 # From a list
series_1 = pd.Series(L)
print(series_1)

arr_1 = [35, 60, 90, 105, 20]    # From an array
series_2 = pd.Series(arr_1)
print(series_2)

dict_of_list = {                 # From a dictionary
    "student_name": "Kedei",
    "score" : "99"
}
series_3 = pd.Series(dict_of_list)
print(series_3)

L2 = [15, 70, 45, 30]                # Using index
index_1 = ['a', 'b', 'c', 'd']
series_4 = pd.Series(L2, index=index_1) 
print(series_4)

0    0
1    1
2    2
3    3
dtype: int64
0     35
1     60
2     90
3    105
4     20
dtype: int64
student_name    Kedei
score              99
dtype: object
a    15
b    70
c    45
d    30
dtype: int64


In [25]:
# Series operations
print(series_1.values)     # Accessing elements using values function

print(series_1[2])         # Indexing

print(series_2[:4])        # Slicing from first index

print(series_3["score"])   # Slicing from the "score" key

print(series_4[2:4])       # Slicing from second to fourth index

[0 1 2 3]
2
0     35
1     60
2     90
3    105
dtype: int64
99
c    45
d    30
dtype: int64


In [26]:
#Creating a dataframe from a dictionary of name, subjects and marks

dict_of_list2 = {
    'Name': ['Josephine', 'Caritas', 'Kayode', 'Alfred'],
    'Courses': ['Management', 'CRE','History', 'English'],
    'Scores': [99, 69, 58, 88]
}

new_df = pd.DataFrame(dict_of_list2)
print(new_df)

        Name     Courses  Scores
0  Josephine  Management      99
1    Caritas         CRE      69
2     Kayode     History      58
3     Alfred     English      88


In [27]:
# Dataframe Operations: Selecting columns
print(new_df['Name'])   # Select the name column
print(new_df[['Name', 'Scores']])    # Select the 'Name' and 'Scores' column

0    Josephine
1      Caritas
2       Kayode
3       Alfred
Name: Name, dtype: object
        Name  Scores
0  Josephine      99
1    Caritas      69
2     Kayode      58
3     Alfred      88


In [28]:
#Filtering Rows
print(new_df.head(2))          # Filter the first two rows
print(new_df.head(3))          # Filter the first three rows
print(new_df.tail(2))          # Filter the last two rows

        Name     Courses  Scores
0  Josephine  Management      99
1    Caritas         CRE      69
        Name     Courses  Scores
0  Josephine  Management      99
1    Caritas         CRE      69
2     Kayode     History      58
     Name  Courses  Scores
2  Kayode  History      58
3  Alfred  English      88


In [29]:
new_df['Grades'] = ['A', 'B', 'C', 'A']   # Add a new column 'Grades' with the given values 'A', 'B', 'C', 'A'
print(new_df)                             # Print updated new_df

        Name     Courses  Scores Grades
0  Josephine  Management      99      A
1    Caritas         CRE      69      B
2     Kayode     History      58      C
3     Alfred     English      88      A


In [30]:
print(new_df.loc[[0, 1]])

        Name     Courses  Scores Grades
0  Josephine  Management      99      A
1    Caritas         CRE      69      B


In [31]:
print(new_df.iloc[1:3,:])

      Name  Courses  Scores Grades
1  Caritas      CRE      69      B
2   Kayode  History      58      C
